@startuml
'https://plantuml.com/sequence-diagram
autonumber "<b>[000]"
skinparam defaultFontName consolas
skinparam sequenceMessageAlign center

=== "Request Make a file" ==
'...5 minutes latter...
Client -> Server:   REQUEST (MakeFile)
Client <-- Server:  ACCEPT-REQUEST (FileManagerStatus)
Client <-- Server:  REJECT-REQUEST (FileManagerStatus)

@enduml
