@startuml
'https://plantuml.com/sequence-diagram
autonumber "<b>[000]"
skinparam defaultFontName consolas
skinparam sequenceMessageAlign center

=== "Request Create a folder" ==
Client -> Server:   REQUEST (CreateFolder)
Client <-- Server:  ACCEPT-REQUEST (FileManagerStatus)
Client <-- Server:  REJECT-REQUEST (FileManagerStatus)

@enduml
