@startuml
'https://plantuml.com/sequence-diagram
autonumber "<b>[000]</b>"
skinparam defaultFontName consolas
skinparam sequenceMessageAlign center

=== "Request Delete a file" ==
Client -> Server:  REQUEST (DeleteFile)
Client <-- Server: ACCEPT-REQUEST (FileManagerStatus)
Client <-- Server: REJECT-REQUEST (FileManagerStatus)

@enduml
